# ┌────────────────────────────────────────────────────────────────────────────+
# │ PXIpLimit 콘피그 파일입니다.
# │ 불필요한 메시지는 지우거나 해당 라인 앞에 '#'을 붇여서 주석 처리해주세요.
# └────────────────────────────────────────────────────────────────────────────+

ipLimit:
  enabled: true
  maxPlayersPerIp: 1

player_info:
  message:
    "
    &f&l-------------------------------\n
    &6플레이어 이름: &f&l{playerName}\n  
    \n
    &a플레이어 IP: &f&l{playerIp}\n
    \n  
    &7동일한 IP 플레이어 수: &f&l{sameIpPlayerNumber}\n
    &7동일한 IP 플레이어: &f&l{sameIpPlayer}\n
    &f&l-------------------------------
    "

